default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") { 'postgres' } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { 'judge0_secret_password' } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { 'db' } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { 5432 } %>

development:
  <<: *default
  database: judge0_development

test:
  <<: *default
  database: judge0_test

production:
  <<: *default
  database: judge0_production
