default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("POSTGRES_HOST", "db") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "postgres") %>
  pool: <%= [
    5,
    ENV.fetch("RAILS_SERVER_PROCESSES", 1).to_i *
    ENV.fetch("RAILS_MAX_THREADS", 5).to_i
  ].max %>

development:
  <<: *default
  database: <%= "#{ENV.fetch('POSTGRES_DB', 'judge0')}_development" %>

test:
  <<: *default
  database: <%= "#{ENV.fetch('POSTGRES_DB', 'judge0')}_test" %>

production:
  <<: *default
  database: <%= "#{ENV.fetch('POSTGRES_DB', 'judge0')}_production" %>
